_clnt.exe : clnt_main.o clnt_func.o low_Level_Func.o
	gcc -o _clnt clnt_main.c clnt_func.c low_Level_Func.c
clnt_main.o : clnt_main.c
	gcc -c clnt_main.c
clnt_func.o : clnt_main.c
	gcc -c clnt_main.c
low_Level_Func.o : low_Level_Func.c
	gcc -c low_Level_Func.c
	

